### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by mherrmann** [rosalexander/oci-object-storage-desktop#1]
Hi,

I'm fbs's author. Your app looks very slick! I hope fbs helps you be successful.

One point: Your project is currently under the LGPL, but it must be under the GPL because you are using fbs. I'm afraid you'll have to 1) change the license 2) get a special (likely commercial) license from me or 3) stop using fbs. Sorry.

Cheers,
Michael

**Comment by rosalexander** [comment]
Hi @mherrmann, thank you for pointing that out and for developing fbs. I have changed the license to GPL.

**Comment by mherrmann** [comment]
No problem. Thanks! :)
